In [ ]:
Continuation

In [2]:
import numpy as np      #import numpy everytime whenever a new notebook is opened.

In [ ]:
#creating an identity matrices

In [2]:
array_eye = np.eye(4)     #4 coz its 4*4 matrix or square matrix

array_eye

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
array_eye2 = np.eye(3)  #3*3 matrix

array_eye2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#req:To create sequence of numbers:   #range in python   #arange in numpy

In [5]:
array_numbers = np.arange(1,20)       #lastvalue is exclusive

array_numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
#req:To create an even  number : 30

In [6]:
array_of_evens = np.arange(2,30,2)   #30 is not printed coz last value is exclusive

array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [7]:
array_of_floats = np.arange(1,20)

array_of_floats

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [8]:
array_of_floats = np.arange(0,3,0.3)             #incremental values of 0.3

array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8, 2.1, 2.4, 2.7])

In [9]:
array_1d = np.array(10)  #1 dimensional array

array_1d

array(10)

In [6]:
array_1d = np.arange(10)

print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
array_1d.shape

(10,)

In [ ]:
#creating 2 dimensional array:

In [8]:
array_2d = np.array([(2,4,6),(3,5,7)])

array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [9]:
array_2d.shape          #(x.y)   2 dimensional matrix

(2, 3)

In [ ]:
#using reshape to crete n dimensional arrays:

In [10]:
x = np.arange(6)

x

array([0, 1, 2, 3, 4, 5])

In [11]:
x.shape

(6,)

In [12]:
x = np.arange(6).reshape(3,2)     #3*2=6....it needs to give primary no. only i.e 6*1 or 3*1 won't work

x

array([[0, 1],
       [2, 3],
       [4, 5]])

In [13]:
x.shape

(3, 2)