In [1]:
import numpy as np

In [ ]:
#printing the arrays

In [ ]:
#1D arrays--->(x),#2D arrays ---->(x,y), #3D array--->(x,y,z)

In [2]:
#1D array

a = np.arange(6)

In [3]:
print(a)

[0 1 2 3 4 5]


In [4]:
a.shape               #(x)..1D array linear shape

(6,)

In [ ]:
#2D arrays

In [5]:
b = np.arange(12).reshape(4*3)

In [6]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
#3D arrays

In [9]:
c = np.arange(24).reshape(2,3,4)    #2*3*4 =24

print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
c.shape        #3D array...(x,y,z)

(2, 3, 4)

In [ ]:
#*Arithmetic operations in numpy:

In [11]:
a = np.array([10,10,10])
b = np.array([2,3,4])

In [12]:
a+b   #addition

array([12, 13, 14])

In [13]:
a-b  #subtraction

array([8, 7, 6])

In [14]:
a*b   #multiply

array([20, 30, 40])

In [15]:
a/b                             #division

array([5.        , 3.33333333, 2.5       ])

In [ ]:
#comparison operation

In [16]:
a<35    #the conditions are validating

array([ True,  True,  True])

In [ ]:
#modifying an existing array rather than create a new one

In [17]:
a += 3

a

array([13, 13, 13])

In [18]:
b += a   #3+5

In [19]:
b          #3+5

array([15, 16, 17])

In [ ]:
#Unary operations

In [20]:
ages = np.array([12,34,67,89,24,35,56])

In [ ]:
#req: to find the minimumm age or small age in the above

In [21]:
ages.min()

12

In [ ]:
#req: to find the maximumm age or biggest age in the above

In [22]:
ages.max()

89

In [ ]:
#req: to find the sum of the age of the shape

In [23]:
ages.sum()

317

In [ ]:
#Understanding axes based caalculation

In [24]:
numbers = np.arange(12).reshape(3,4)

numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
numbers.shape    #2D array

(3, 4)

In [ ]:
#in a 2D array  axis 0 is columns  and axis 1 is rows

In [27]:
numbers.sum(axis=0)   #sum of all the cols

array([12, 15, 18, 21])

In [ ]:
#req :  to find out sum of each row

In [28]:
numbers.sum(axis=1)

array([ 6, 22, 38])

In [ ]:
#req: minimum value of each row

In [29]:
numbers.min(axis=1)

array([0, 4, 8])