In [ ]:
Introduction to Numpy

Numpy is majorly used to do the numerical techniques

In [2]:
#installation of numpy

!pip install numpy

In [22]:
!pip install numpy

In [23]:
!pip install numpy

In [24]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\sanjarlappy\anaconda3\python\lib\site-packages (1.19.1)


In [29]:
Getting started with numpy:
    
Import numpy as np #np-->numpy--->np    ......always to be done

SyntaxError: invalid syntax (<ipython-input-29-6fe348067aba>, line 1)

In [1]:
import numpy as np #np-->numpy--->np 

In [ ]:
#understanding numpy it is majorly used in numerical computations

In [ ]:
#it forms as a primary layer in the scientific computations and work with high end algorithms

In [ ]:
*Understanding the datatypes of Numpy: ***!
    
Numpy will be having a default datatype called as array....(list)    

interview quest****imp
What is difference btw array and a list?
What do u choose btw an array and a list?....explain why

In [2]:
a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [3]:
type(a)              #nd----n dimensions

numpy.ndarray

In [5]:
b = np.array([1,2],[3,4])

print(b)

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [6]:
b = np.array([[1,2],[3,4]])

print(b)

[[1 2]
 [3 4]]


In [ ]:
#Calculations:-  Matrices

In [7]:
number = [9,8,7,6,5]

In [9]:
x = np.array(number)
print(x)

[9 8 7 6 5]


In [10]:
array_of_zeros = np.zeros((3,4))    #3rows, 4columns

print(array_of_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
array_of_ones = np.ones((4,5))       #internally arrays will be using float datatype, so there are . in one n zeros

print(array_of_ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
type(array_of_ones)

numpy.ndarray

In [13]:
array_of_ones_int = np.ones((3,4), dtype=np.int16)    #int16, int32, int64

print(array_of_ones_int)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
#interview quest

how do you eliminate the decimals appearing in the array?
ans...By specifying the datatype in the array